# Generated by Django 4.2.9 on 2024-05-06 15:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300)),
                ('done', models.BooleanField(default=False)),
                ('taskDescription', models.TextField(null=True)),
                ('task_Assign_Date', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField(null=True)),
                ('importance', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('College', 'College'), ('Mindfulness', 'Mindfulness')], default='Fitness', max_length=20)),
                ('choice', models.CharField(default='null', max_length=100)),
                ('manage', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
