# Generated by Django 4.2.9 on 2024-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_tasklist_deadline_tasklist_importance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklist",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
