# Generated by Django 4.2.7 on 2024-04-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='choice',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
