# Generated by Django 4.2.9 on 2024-04-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_tasklist_points"),
        ("todo", "0006_alter_tasklist_choice"),
    ]

    operations = []
