# Generated by Django 4.2.9 on 2024-04-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
