# Generated by Django 4.2.9 on 2024-03-13 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='taskAssignDate',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='task_Assign_Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='taskDescription',
            field=models.TextField(null=True),
        ),
    ]
