# Generated by Django 4.2.7 on 2023-12-08 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskmodel_taskassigndate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='taskAssignDate',
            new_name='task_Assign_Date',
        ),
    ]
